#version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: quant
      POSTGRES_PASSWORD: quant123
      POSTGRES_DB: quantdb
    ports:
      - "8080:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quant_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@quant.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      SERVER_MODE: "True"
      GUNICORN_CMD_ARGS: "--bind 0.0.0.0:80"
    ports:
      - "8081:80"
      - "8443:443"
    networks:
      - quant_network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  quant_network:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 172.20.0.0/16
