# .streamlit/secrets.toml
# 这是一个示例配置文件，请勿在此处存储真实敏感信息
# 实际部署时请使用环境变量或安全配置管理系统

[connections.my_database]
dialect = "mysql"
host = "localhost"
port = 3306
database = "your_database_name"
username = "your_username"
password = "${DB_PASSWORD}"  # 使用环境变量引用
